### ISSUE TITLE
Dialog disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/Weather#10]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on ... to open action overflow menu
2. Click on Create Shortcut
3. Device Rotation

Sequence 2:
1. Click on ... to open action overflow menu
2. Click on Settings
3. Click on
a. Tabs: main screen
b. Tabs: weather
c. State
d. App start and title bar click
e. License
4. Orientation Change

**Comment by scoute-dich** [comment]
Since you know, that is the default behavior of android. When changing orientation the view gets recreated. Since that is not a problem for me or other users I won't do anything concerning this issue. And yes I know that you are "exploring mobile GUI failures for research purposes". I wish you luck with your project.
