### ISSUE TITLE
Still background connection to Google

### ISSUE THREAD

**Issue by lufticus** [scoute-dich/Weather#35]
Blokada **still** reports an attempt to connect to **fonts.googleapis.com** or **ajax.googleapis.com** when the app starts or when changing location or forecast-view. This should not be the case with F-Droid app!

**Comment by techge** [comment]
To be fair, I guess this is because dwd uses Google fonts, not because @scoute-dich wants this to happen... I am sure that they will work on it.

**Comment by scoute-dich** [comment]
Ok. Thanks for information. Fact is, that the app only shows websites inside a webview. I can not influence what happens on the websites.

But I can try to block unwanted addresses. So if there are more than post it here. At the moment I don't have much time, since I'm working as teacher in real life, and we just reopened schools today in Germany...

**Comment by scoute-dich** [comment]
- fonts.googleapis.com: is now blocked
- ajax.googleapis.com: is necessary for opening menus on wetterdienst.de (at least it seems so for me)

Regards
Gaukler Faun
