### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/Weather#8]
When I perform this sequence of events, the scroll view on screen goes back to the top

Sequence 1:
1. In the Main screen dialog, scroll down
2. Orientation Change

Sequence 2:
1. Click on Weather Infos item in list
2. Scroll Down
3. Orientation Change

Sequence 3: 
1. Click on Bookmarks
2. Click on item in list
3. Scroll Down
4. Orientation Change

Sequence 4:
1. Click on ...
2. Click on Settings
3. Scroll Down
4. Orientation Change

**Comment by scoute-dich** [comment]
Since you know, that is the default behavior of android. When changing orientation the view gets recreated. Since that is not a problem for me or other users I won't do anything concerning this issue. And yes I know that you are "exploring mobile GUI failures for research purposes". I wish you luck with your project.
