### ISSUE TITLE
Dialog appear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/Weather#9]
When I perform this sequence of events, an unwanted dialog appear on the screen

1. In Used permissions dialog click on Cancel
2. Click Cancel
3. Orientation Change

**Comment by scoute-dich** [comment]
Since you know, that is the default behavior of android. When changing orientation the view gets recreated. Since that is not a problem for me or other users I won't do anything concerning this issue. And yes I know that you are "exploring mobile GUI failures for research purposes". I wish you luck with your project.
